# title of website
title: hao

# description of website
description: adon68's navigation site

# favicon of website
favicon: "https://github.com/adon68.png?size=40"

# your website url
url: https://adon68.github.io/hao/

# github profile url
github: "https://github.com/adon68"

# footer message
footer: © 2021-2021 @adon68

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR12"

webstack:
  search:
    enabled: false
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: 热门推荐
      sites:
        - name: gitea
          description: （LDAP）代码托管仓库
          url: http://pang.honglei.vip:11400
        - name: JumpServer
          description: （LDAP）堡垒机
          url: http://pang.honglei.vip:1088
        - name: SonarQube
          description: （LDAP）代码质量扫描
          url: http://www.ui.cn/
    - name: 常用推荐
      sites:
        - name: 蓝湖
          description: 高效的产品设计协作平台
          url: https://lanhuapp.com/web/#/user/login
        - name: 飞书
          description: 先进企业协作与管理平台
          url: https://b8ijl3262y.feishu.cn/messenger/
        - name: Jenkines
          description: （LADP）持续集成与持续部署
          url: https://ci.hcece.com/
        - name: TAPD
          description: 一站式敏捷研发协作云平台
          url: https://www.tapd.cn/cloud_logins/login
    - name: 在线工具
      sites:
        - name: 帮小忙，万能工具宝藏
          description: 功能一应俱全、简单好用的线上工具库
          url: https://tool.browser.qq.com/
        - name: TableConvert
          description: 在线表格编辑
          url: https://tableconvert.com/
        - name: TXT文本处理工具
          description: 在线TXT文本处理工具
          url: http://www.txttool.com/
        - name: CRON表达式
          description: Crontab执行时间计算
          url: https://tool.lu/crontab/
        - name: BeJSON
          description: 在线JSON校验格式化工具
          url: https://www.bejson.com/
